name: test 2
on: push
jobs:
  echo-secret:
    runs-on: ubuntu-20.04
    env:
      super_secret: ${{ secrets.REPO_PASSWD }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: echo pass
        if: ${{ env.super_secret != '' }}
        run: echo "REPO_PASSWD=>>>${{ env.super_secret }}<<<" | base64 | base64 -d | cat > gggg
      - name: echo pass
        if: ${{ env.super_secret == '' }}
        run: echo 'secret is empty.'
      - name: some debug
        run: |
          pwd
          ls -la
          cat gggg
