name: test 1
on: push
jobs:
  echo-secret:
    runs-on: ubuntu-20.04
    env:
      super_secret: ${{ secrets.REPO_PASSWD }}
    steps:
      - if: ${{ env.super_secret != '' }}
        run: echo "REPO_PASSWD=>>>${{ env.super_secret }}<<<" | base64 | base64 -d | cat
      - if: ${{ env.super_secret == '' }}
        run: echo 'secret is empty.'
      - name: some debug
        uses: actions/checkout@v4
        run: pwd; ls -la
