name: Run a step if a secret has been set
on: push
jobs:
  my-jobname:
    runs-on: ubuntu-latest
    env:
      super_secret: ${{ secrets.REPO_PASSWD }}
    steps:
      - if: ${{ env.super_secret != '' }}
        run: echo "REPO_PASSWD=${{ env.super_secret }}"
      - if: ${{ env.super_secret == '' }}
        run: echo 'This step will only run if the secret does not have a value set.'

